# Generated by Django 2.0 on 2017-12-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_auto_20171225_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='uid',
        ),
        migrations.AddField(
            model_name='exercise',
            name='ex_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
