# Generated by Django 2.0 on 2017-12-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_auto_20171225_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='ex_id',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
