# Generated by Django 2.0 on 2017-12-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_exercise_media_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='media_file',
            field=models.FileField(default=1, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
