# Generated by Django 2.0 on 2017-12-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_exercise_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='media_file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
