# Generated by Django 2.0 on 2017-12-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_auto_20171225_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='media_file',
            field=models.FileField(upload_to='fitness/'),
        ),
    ]
