# Generated by Django 2.0 on 2017-12-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_auto_20171226_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='media_link',
        ),
        migrations.AddField(
            model_name='exercise',
            name='repetitions',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=4),
            preserve_default=False,
        ),
    ]
