# Generated by Django 2.0 on 2017-12-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_auto_20171226_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='in_prog',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
