# Generated by Django 2.0 on 2017-12-26 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_auto_20171226_2204'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='exercise',
            order_with_respect_to=None,
        ),
    ]
