# Generated by Django 2.0 on 2017-12-26 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0017_auto_20171226_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['order'], 'verbose_name': 'Exercise', 'verbose_name_plural': 'Exercises'},
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='prog_order',
            new_name='order',
        ),
    ]
