# Generated by Django 2.0 on 2018-01-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0018_auto_20171226_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='hold_position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
