# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fahrt_bezeichner', models.CharField(max_length=20)),
                ('bpuic', models.IntegerField()),
                ('haltestellen_name', models.CharField(max_length=50)),
                ('linien_text', models.CharField(max_length=20)),
                ('betriebstag', models.DateTimeField()),
                ('ankunftszeit', models.DateTimeField()),
                ('an_prognose', models.DateTimeField()),
                ('an_prognose_status', models.CharField(max_length=20)),
                ('abfahrtszeit', models.DateTimeField()),
                ('ab_prognose', models.DateTimeField()),
                ('ab_prognose_status', models.CharField(max_length=20)),
                ('faellt_aus_tf', models.CharField(max_length=20)),
                ('ab_delay', models.CharField(max_length=20)),
            ],
        ),
    ]
