# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='ab_prognose',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='an_prognose',
            field=models.DateTimeField(null=True),
        ),
    ]
