# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20171210_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='ab_delay',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
