# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20171210_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='id',
        ),
        migrations.AddField(
            model_name='train',
            name='uid',
            field=models.CharField(default=1, max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
