# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sbbdelay3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='ab_delay',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
