# Generated by Django 2.0 on 2017-12-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='faellt_aus_tf',
            field=models.IntegerField(),
        ),
    ]
