# Generated by Django 2.0 on 2017-12-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delay', '0003_auto_20171228_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='abfahrtszeit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='ankunftszeit',
            field=models.DateTimeField(null=True),
        ),
    ]
