# Generated by Django 2.0 on 2017-12-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delay', '0004_auto_20171228_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='ab_prognose_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='an_prognose_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
